// Generated by CoffeeScript 1.8.0
var absolutePaths, fixture, fixtures, path, _i, _len;

path = require('path');

absolutePaths = {};

fixtures = ['indentation', 'intersection', 'intersection-diff', 'no-match'];

for (_i = 0, _len = fixtures.length; _i < _len; _i++) {
  fixture = fixtures[_i];
  absolutePaths[fixture] = path.resolve(__dirname, fixture + '.scss');
}

module.exports = absolutePaths;
