// Generated by CoffeeScript 1.8.0
var astToCSS,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

astToCSS = function(options) {
  var hasInfo, index, syntax, tree, _composite, _m_composite, _m_primitive, _m_simple, _simple, _suppressed, _t, _unique;
  _t = function(tree) {
    var e, t;
    t = tree[index(0)];
    try {
      if (__indexOf.call(Object.keys(_m_primitive), t) >= 0) {
        return _m_primitive[t];
      } else if (__indexOf.call(Object.keys(_m_simple), t) >= 0) {
        return _simple(tree);
      } else if (__indexOf.call(Object.keys(_m_composite), t) >= 0) {
        return _composite(tree);
      } else if (__indexOf.call(_suppressed, t) >= 0) {
        return '';
      } else {
        return _unique[t](tree);
      }
    } catch (_error) {
      e = _error;
      return "[__ERROR__:" + tree + "]";
    }
  };
  _composite = function(t, i) {
    var token;
    if (i == null) {
      i = index(1);
    }
    return ((function() {
      var _i, _len, _ref, _results;
      _ref = t.slice(i);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        token = _ref[_i];
        _results.push(_t(token));
      }
      return _results;
    })()).sort().join('');
  };
  _simple = function(t) {
    return t[index(1)];
  };
  if (!options) {
    throw new Error('We need tree to translate');
  }
  tree = typeof options === 'string' ? options : options.ast;
  hasInfo = typeof tree[0] === 'object';
  syntax = options.syntax || 'css';
  index = function(i) {
    if (hasInfo) {
      return i + 1;
    } else {
      return i;
    }
  };
  _m_simple = {
    'attrselector': 1,
    'combinator': 1,
    'ident': 1,
    'nth': 1,
    'number': 1,
    'operator': 1,
    'raw': 1,
    'string': 1,
    'unary': 1,
    'unknown': 1
  };
  _m_composite = {
    'atruleb': 1,
    'atrulerq': 1,
    'atrulers': 1,
    'atrules': 1,
    'condition': 1,
    'dimension': 1,
    'filterv': 1,
    'include': 1,
    'loop': 1,
    'mixin': 1,
    'simpleselector': 1,
    'progid': 1,
    'property': 1,
    'ruleset': 1,
    'stylesheet': 1,
    'value2': 1
  };
  _m_primitive = {
    'cdc': 'cdc',
    'cdo': 'cdo',
    'declDelim': '',
    'delim': '',
    'namespace': '|',
    'parentselector': '&',
    'propertyDelim': ':'
  };
  _unique = {
    'arguments': function(t) {
      return '(' + _composite(t) + ')';
    },
    'atkeyword': function(t) {
      return '@' + _t(t[index(1)]);
    },
    'atruler': function(t) {
      return _t(t[index(1)]) + _t(t[index(2)]) + '{' + _t(t[index(3)]) + '}';
    },
    'attrib': function(t) {
      return '[' + _composite(t) + ']';
    },
    'block': function(t) {
      var rules, rulesText, token;
      rules = ((function() {
        var _i, _len, _ref, _results;
        _ref = t.slice(index(1));
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          token = _ref[_i];
          _results.push(_t(token));
        }
        return _results;
      })()).filter(function(s) {
        return s.length > 0;
      });
      rulesText = rules.sort().join('; ');
      if (syntax === 'sass') {
        return rulesText;
      } else {
        return '{ ' + rulesText + ' }';
      }
    },
    'braces': function(t) {
      return t[index(1)] + _composite(t, index(3)) + t[index(2)];
    },
    'class': function(t) {
      return '.' + _t(t[index(1)]);
    },
    'declaration': function(t) {
      var token;
      return ((function() {
        var _i, _len, _ref, _results;
        _ref = t.slice(index(1));
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          token = _ref[_i];
          _results.push(_t(token));
        }
        return _results;
      })()).join('');
    },
    'selector': function(t) {
      var token;
      return ((function() {
        var _i, _len, _ref, _results;
        _ref = t.slice(index(1));
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          token = _ref[_i];
          _results.push(_t(token));
        }
        return _results;
      })()).filter(function(s) {
        return s.length > 0;
      }).sort().join(', ') + ' ';
    },
    'value': function(t) {
      var token;
      return ((function() {
        var _i, _len, _ref, _results;
        _ref = t.slice(index(1));
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          token = _ref[_i];
          _results.push(_t(token));
        }
        return _results;
      })()).filter(function(s) {
        return s.length > 0;
      }).join(' ');
    },
    'default': function(t) {
      return '!' + _composite(t) + 'default';
    },
    'escapedString': function(t) {
      return '~' + t[index(1)];
    },
    'filter': function(t) {
      return _t(t[index(1)]) + ':' + _t(t[index(2)]);
    },
    'functionExpression': function(t) {
      return 'expression(' + t[index(1)] + ')';
    },
    'function': function(t) {
      return _simple(t[index(1)]) + '(' + _composite(t[hasInfo ? 3 : 2]) + ')';
    },
    'important': function(t) {
      return '!' + _composite(t) + 'important';
    },
    'interpolatedVariable': function(t) {
      return (syntax === 'less' ? '@{' : '#{$') + _t(t[index(1)]) + '}';
    },
    'nthselector': function(t) {
      return ':' + _simple(t[index(1)]) + '(' + _composite(t, index(2)) + ')';
    },
    'percentage': function(t) {
      return _t(t[index(1)]) + '%';
    },
    'placeholder': function(t) {
      return '%' + _t(t[index(1)]);
    },
    'pseudoc': function(t) {
      return ':' + _t(t[index(1)]);
    },
    'pseudoe': function(t) {
      return '::' + _t(t[index(1)]);
    },
    'shash': function(t) {
      return '#' + t[index(1)];
    },
    'uri': function(t) {
      return 'url(' + _composite(t) + ')';
    },
    'variable': function(t) {
      return (syntax === 'less' ? '@' : '$') + _t(t[index(1)]);
    },
    'variableslist': function(t) {
      return _t(t[index(1)]) + '...';
    },
    'vhash': function(t) {
      return '#' + t[index(1)];
    }
  };
  _suppressed = ['s', 'commentML', 'commentSL'];
  return _t(tree);
};

exports.astToCSS = astToCSS;
